[package]
name = "ironarm"
version = "0.1.0"
edition = "2024"

[features]
default = ["std"]
std = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9" 

